# name: Deploy Python project to Azure Function App

# on:
#   push:
#     branches: ["main"]
#     paths:
#       - 'backend/**'

# env:
#   AZURE_FUNCTIONAPP_NAME: 'func-learn-ai-fgbze4djd2dhh5hm'
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
#   PYTHON_VERSION: '3.12'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: 'Checkout GitHub Action'
#       uses: actions/checkout@v3

#     - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ env.PYTHON_VERSION }}


#     - name: 'Run Azure Functions Action'
#       uses: Azure/functions-action@v1
#       id: fa
#       with:
#         app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#         package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#         publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
#         scm-do-build-during-deployment: true
#         enable-oryx-build: true
